--- 
services: 
  fedManager:
    build: .
    tty: true
    image: ""
    command: "sh start.sh FedManager"
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1
    extra_hosts:
      - "cpswtng_archiva:"
    volumes:
      - undefined/input//fedManager:/root/Projects/c2wt/input
      - undefined/output//fedManager:/root/Projects/c2wt/logs
  JavaFederate_Communication_0:
    build: .
    image: ""
    command: "sh start.sh Communication,ExecJava" 
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1
    extra_hosts:
      - "cpswtng_archiva:"
    links:
      - fedManager  
    volumes:
      - undefined/input//JavaFederate_Communication_0:/root/Projects/c2wt/input
      - undefined/output//JavaFederate_Communication_0:/root/Projects/c2wt/logs
  JavaFederate_Control_0:
    build: .
    image: ""
    command: "sh start.sh Control,ExecJava" 
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1
    extra_hosts:
      - "cpswtng_archiva:"
    links:
      - fedManager  
    volumes:
      - undefined/input//JavaFederate_Control_0:/root/Projects/c2wt/input
      - undefined/output//JavaFederate_Control_0:/root/Projects/c2wt/logs
  JavaFederate_Sensing_0:
    build: .
    image: ""
    command: "sh start.sh Sensing,ExecJava" 
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1
    extra_hosts:
      - "cpswtng_archiva:"
    links:
      - fedManager  
    volumes:
      - undefined/input//JavaFederate_Sensing_0:/root/Projects/c2wt/input
      - undefined/output//JavaFederate_Sensing_0:/root/Projects/c2wt/logs
version: "2.1"
